name: CI/CD

on:
  push:
  pull_request:

env:
  AWS_REGION : "eu-west-1"
  NODE_VERSION: 16.x

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Test code
        uses: noi-techpark/github-actions/npm-test@v2
        with:
          working-directory: databrowser
          node-version: ${{ env.NODE_VERSION }}
          test-enabled: false

  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/development'
    needs: test
    concurrency: deploy-test
    env:
      AWS_S3_BUCKET_NAME : "it.bz.opendatahub.databrowser-test"
      VITE_APP_KEYCLOAK_URL: "https://auth.opendatahub.testingmachine.eu/auth"
      VITE_APP_KEYCLOAK_REALM: "noi"
      VITE_APP_KEYCLOAK_CLIENT_ID: "it.bz.opendatahub.databrowser"
      VITE_APP_KEYCLOAK_REDIRECT_URI: "https://databrowser.opendatahub.testingmachine.eu/silent-check-sso.html"
      VITE_APP_IMAGE_UPLOAD_URL: "https://api.tourism.testingmachine.eu/v1/FileUpload/Image"
      VITE_APP_FILE_UPLOAD_URL: "https://api.tourism.testingmachine.eu/v1/FileUpload/"
      VITE_APP_ODH_LOOKUP_BASE_URL: "https://api.tourism.testingmachine.eu"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build code
        uses: noi-techpark/github-actions/npm-build@v2
        with:
          working-directory: databrowser
          node-version: ${{ env.NODE_VERSION }}
      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
        with:
          working-directory: databrowser
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./dist

  deploy-prod:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: deploy-prod
    env:
      AWS_S3_BUCKET_NAME : "it.bz.opendatahub.databrowser-prod"
      VITE_APP_KEYCLOAK_URL: "https://auth.opendatahub.com/auth"
      VITE_APP_KEYCLOAK_REALM: "noi"
      VITE_APP_KEYCLOAK_CLIENT_ID: "it.bz.opendatahub.databrowser"
      VITE_APP_KEYCLOAK_REDIRECT_URI: "https://databrowser.opendatahub.bz.it/silent-check-sso.html"
      VITE_APP_IMAGE_UPLOAD_URL: "https://tourism.opendatahub.bz.it/v1/FileUpload/Image"
      VITE_APP_FILE_UPLOAD_URL: "https://tourism.opendatahub.bz.it/v1/FileUpload"
      VITE_APP_ODH_LOOKUP_BASE_URL: "https://tourism.opendatahub.bz.it"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build code
        uses: noi-techpark/github-actions/npm-build@v2
        with:
          working-directory: databrowser
          node-version: ${{ env.NODE_VERSION }}
      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
        with:
          working-directory: databrowser
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./dist
